### ISSUE TITLE
Comments for "A Foray Into Home Automation"

### ISSUE THREAD

**Issue by omgmog** [omgmog/omgmog.github.com#102]
You can view the blog post here: [A Foray Into Home Automation](https://blog.omgmog.net/post/a-foray-into-home-automation/)

Any replies to this issue will be viewable at the end of the post.

**Comment by oerman35** [comment]
This is awesome, thanks for the blog post. I'm keen to try it out 😁  I have one question... _Are you still able to flick the light switch manually, using your finger, or does the servo prevent you from doing so?_

I recently started experimenting with some DIY projects using a Wemos board (similar to the NodeMCU), and my first project was automating my garage door. I hooked it up to my Google Assistant using IFTTT and also built my own web app in Angular and .Net to control it. My next project might just be this one of yours 😁

**Comment by omgmog** [comment]
With the plate I designed originally you could sort of manually manipulate the servo out of the way to flip the switch, but it wasn't what I would call completely accessible! 

I had plans to make a version where the servo could be rotated out of the way, but in the end (and after an office re-shuffle) I ended up uninstalling the automation from the light switch...

Maybe if I get bored in the future I'll revisit this!
