### ISSUE TITLE
Comments for "Pico-8 on the Raspberry Pi with Game HAT"

### ISSUE THREAD

**Issue by omgmog** [omgmog/omgmog.github.com#104]
You can view the blog post here: [Pico-8 on the Raspberry Pi with Game HAT](https://blog.omgmog.net/post/pico8-on-the-raspberrypi-with-gamehat/)

Any replies to this issue will be viewable at the end of the post.

**Comment by M1ch3L5** [comment]
Hello,

i have prepared my raspi and Game HAT as described in the blog. I have installed retropi, added the configuration for the arcade_joysick_rpi, copied the Pico-8, install the wiringpi und modify the retropiscript. It works fine but i am not possible to use the joystick and the buttons in Pico-8. So my question:
Is it necessary to install the mk_arcade_joystick_rpi? The retropi simulation works fine.
How is the correct key configuration to use the buttons and the joystick? What i have to do?

It would be fine to get some hints.

Your Volker

**Comment by omgmog** [comment]
Hi there, unfortunately I'm using my Pi in another project now so can't confirm the settings.

You could try setting up the Game HAT manually as per the instructions here: https://www.waveshare.com/w/upload/2/22/Game_HAT_user_manual_en.pdf

and then follow my instructions for installing pico8 and making the changes in `/etc/profile.d/10-retropie.sh`

Hope that helps!
