### ISSUE TITLE
Comments for "The Raspberry Pi Pico and the Pimoroni Pico RGB Keypad"

### ISSUE THREAD

**Issue by omgmog** [omgmog/omgmog.github.com#108]
You can view the blog post here: [The Raspberry Pi Pico and the Pimoroni Pico RGB Keypad](https://blog.omgmog.net/post/the-raspberry-pi-pico-and-pimoroni-rgp-keypad/)

Any replies to this issue will be viewable at the end of the post.

**Comment by qbalsdon** [comment]
Thanks for the reference!

**Comment by omgmog** [comment]
> Thanks for the reference!

Thanks for creating such a great example program for the keypad! Your [pico_rgb_keypad_hid](https://github.com/qbalsdon/pico_rgb_keypad_hid) repo has been a great starting point.

**Comment by 1jammer1** [comment]
Very cool thanks for sharing it
