### ISSUE TITLE
compresspdf (.bash_profile) files with Space: No such file or directory

### ISSUE THREAD

**Issue by idarek** [omgmog/omgmog.github.com#11]
Hi,
Nice script. 

Have you got any idea how to make it less sensitive when files contain space in filename?

`compresspdf "Download\ Day\ 2008.pdf" dd.pdf`

Than:
`

Error: /undefinedfilename in (Download\\)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:1206/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.21: Unrecoverable error, exit code 1

`

**Comment by omgmog** [comment]
Might probably be better (looking at my original function) to wrap the arguments in quotes when used:

```shell
ompresspdf() {
    gs -sDEVICE=pdfwrite -dNOPAUSE -dQUIET -dBATCH -dPDFSETTINGS=/${3:-"screen"} -dCompatibilityLevel=1.4 -sOutputFile="$2" "$1"
}
```

And then you can call it with your files:

```shell
compresspdf Download\ Day\ 2008.pdf dd.pdf
```

The escaped spaces should be handled correctly when `gs` is called then.

**Comment by idarek** [comment]
Thanks, sorted, but than filenames need to be in " "

ie. 
`compresspdf "filename 1.pdf" "filename 2.pdf"`

👍
