### ISSUE TITLE
Comments for "Installing Arch Linux ARM on the HP Chromebook 11"

### ISSUE THREAD

**Issue by omgmog** [omgmog/omgmog.github.com#95]
You can view the blog post here: [Installing Arch Linux ARM on the HP Chromebook 11](https://blog.omgmog.net/post/installing-arch-linux-arm-on-the-hp-chromebook-11)

Any replies to this issue will be viewable at the end of the post.

**Comment by mikailkaan** [comment]
Hi, I have a problem with the installation of the install.sh. It keeps saying "-su: wget: command not found"
